name: Create tag

on:
  workflow_dispatch:
    inputs:
      semver:
        description: "The tag version it is going to be created. Please make sure version number starts with 'v' (for example: v1.0.0, v2.1.2, etc.)"
        required: true
        type: "string"

jobs:
  tag:
    uses: crisszkutnik/gh-actions/.github/workflows/tag-js.yaml@main
    with:
      semver: ${{ inputs.semver }}
    permissions:
      contents: write
    secrets:
      ACTIONS_PERSONAL_ACCESS_TOKEN: ${{ secrets.ACTIONS_PERSONAL_ACCESS_TOKEN }}